version: '3.4'
services:
 ####angular####
  angular: 
    container_name: docker_angular
    image: frontimage
    build: 
      context: ./AgenceDeVoyage
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
       ####express####
  express:
    image: backimage
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mysql 
    
  ####mysql####
  mysql:
    container_name: docker_mysql
    image: mysql:latest
    ports:
    - '3306:3306'
    


 